server:
  port: 3377

spring:
  application:
    name: nacos-config-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.01:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: DEV_GROUP